<a href="https://colab.research.google.com/github/spctr01/PyTorch/blob/master/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import torch


# **numpy array**

In [7]:
array = [[1,2,3],[4,5,6]]
a_array = np.array(array)
print("array--{}\n  type{}\n shape{}".format(a_array,
                                                   type(a_array),
                                                   np.shape(a_array)  ))

array--[[1 2 3]
 [4 5 6]]
  type<class 'numpy.ndarray'>
 shape(2, 3)



# **pytorch array/tensor**

In [12]:
tensor = torch.tensor(array)
print("type--{}\n shape--{}\n".format(tensor.type, tensor.shape))

type--<built-in method type of Tensor object at 0x7fb2db85f510>
 shape--torch.Size([2, 3])



# **random / ones**

In [15]:
print("np_ones: {}\n np_randoms{}\n".format(np.ones((2,3)),
                                        np.random.rand(2,3) ))

print("\n torch_ones:{}\n torch_randoms:{}".format(torch.ones((2,3)),
                                                  torch.rand(2,3) ))

np_ones: [[1. 1. 1.]
 [1. 1. 1.]]
 np_randoms[[0.5865518  0.12020438 0.51134997]
 [0.36620638 0.45430957 0.32802573]]


 torch_ones:tensor([[1., 1., 1.],
        [1., 1., 1.]])
 torch_randoms:tensor([[0.6413, 0.7835, 0.8057],
        [0.6860, 0.9018, 0.6061]])


# **numpy to tensor**

In [19]:
array = np.random.rand(2,3)
tensor = torch.from_numpy(array)

print("array:{}\n{} \n\n tensor:{}\n{}".format(type(array),array,
                                            tensor.type,tensor))

array:<class 'numpy.ndarray'>
[[0.54245124 0.70920796 0.26788904]
 [0.62812413 0.610232   0.59182404]] 

 tensor:<built-in method type of Tensor object at 0x7fb2db81f6c0>
tensor([[0.5425, 0.7092, 0.2679],
        [0.6281, 0.6102, 0.5918]], dtype=torch.float64)


In [30]:
tensor = torch.ones(3,3)
print(tensor)

#Resize
print(tensor.view(-1).shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9])
